xpack:
  security:
    enabled: false

preInstall:
  enabled: false

env:
  ELASTICSEARCH_HOSTS: '["http://elasticsearch-master:9200"]'
  XPACK_SECURITY_ENABLED: "false"

service:
  type: NodePort
  port: 5601
  nodePort: 30601

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"


