services:
  backend:
    image: nobugsme/nbank:with_validation_fix
    ports:
      - "4111:4111"
    networks:
      - nbank-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4111/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    image: nobugsme/nbank-ui:with_nginx
    expose: # не открываем порт наружу, а даем доступ контейнерам в сети
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nbank-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://frontend" ]
      interval: 10s
      timeout: 5s
      retries: 10

  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: ["-container-network", "nbank-network"]
    depends_on:
      - frontend
    networks:
      - nbank-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    depends_on:
      - selenoid
    networks:
      - nbank-network

networks:
  nbank-network:
    name: nbank-network